services:
  - type: web
    name: todo-api
    runtime: dotnet
    branch: main
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/TodoApiNovo.dll
    publishPath: out
    region: oregon
    plan: free