services:
  - type: web
    name: todo-api
    runtime: docker
    branch: main
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: PORT
        value: 10000
    plan: free
    region: oregon