services:
  - type: web
    name: todo-api
    runtime: docker
    plan: free
    branch: main
    region: oregon
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 10000